**Import**

In [67]:
from __future__ import print_function
import os
data_path = ['.']

import numpy as np
import pandas as pd

**Open CSV file**

In [75]:
filepath = os.sep.join(data_path + ['cases_malaysia.csv'])
data = pd.read_csv(filepath)

**Create the mask for selecting date range**

In [72]:
start_date = '2022-01-01'
end_date = '2022-06-30'
mask = (data['date'] >= start_date) & (data['date'] <= end_date)

**Update the dataframe within date range**

In [76]:
data=data.loc[mask]
data

,date,cases_new,cases_import,cases_recovered,cases_active,cases_cluster,cases_unvax,cases_pvax,cases_fvax,cases_boost,...,cases_60_69,cases_70_79,cases_80,cluster_import,cluster_religious,cluster_community,cluster_highRisk,cluster_education,cluster_detentionCentre,cluster_workplace
707,2022-01-01,3386,346,3547,40943,211,769,16,2292,309,...,263,108,34,8.0,2.0,9.0,5.0,4.0,70.0,113.0
708,2022-01-02,2882,333,3291,40516,103,585,18,2038,241,...,243,97,32,2.0,1.0,2.0,2.0,16.0,53.0,27.0
709,2022-01-03,2690,300,3535,39651,55,539,20,1861,270,...,244,100,32,15.0,0.0,1.0,2.0,9.0,0.0,28.0
710,2022-01-04,2842,332,2862,39615,33,674,14,1882,272,...,222,109,37,4.0,2.0,1.0,1.0,16.0,0.0,9.0
711,2022-01-05,3270,252,3195,39664,61,706,15,2238,311,...,273,137,35,6.0,0.0,2.0,26.0,4.0,0.0,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,2022-06-26,2003,3,1861,28137,1,169,20,364,1450,...,99,55,31,0.0,0.0,0.0,0.0,1.0,0.0,0.0
884,2022-06-27,1894,6,1944,28082,9,156,21,361,1356,...,105,66,48,0.0,0.0,0.0,0.0,9.0,0.0,0.0
885,2022-06-28,2025,20,2367,27737,2,176,24,425,1400,...,103,77,37,0.0,0.0,0.0,1.0,1.0,0.0,0.0
886,2022-06-29,2605,3,1633,28706,0,200,26,547,1832,...,129,51,36,0.0,0.0,0.0,0.0,0.0,0.0,0.0
887,2022-06-30,2867,4,2145,29426,6,246,14,545,2062,...,139,79,45,0.0,0.0,0.0,0.0,6.0,0.0,0.0